services:
  mysql:
    image: mysql:8.0
    container_name: survey-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 初期データがある場合
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: